[package]
name = "llm_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
bincode = "2.0.1"
half = "2.6.0"
lazy_static = "1.5.0"
packed_simd_2 = "0.3.8"
rand = "0.9.1"
rayon = "1.10.0"
serde = "1.0.219"
